/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'masamitsu' at '15/11/03 23:33' with Gradle 2.6
 *
 * @author masamitsu, @date 15/11/03 23:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
